JuliaData/SentinelArrays.jl

src/SentinelArrays.jl, src/chainedvector.jl, test/runtests.jl
This was another piece of functionality that was slightly half-baked,
not fully tested in CSV.jl. When multi-threaded parsing is used in
CSV.jl, each thread produces a column "chunk" which get "chained"
together after parsing. This implementation includes a field for the
chained arrays, as well as a field for the last "indexes" for each
chunk. This allows for efficient use of `searchsortedfirst`, a binary
search function in Base to index individual elements.
We technically allow chaining any `AbstractVector`, but mutable
operations will require the chained array type to support mutable
operations as well; e.g. to `insert!` into a ChainedVector, we need to
be able to `insert!` into the underlying array.
=> Implement a ChainedVector array type for chaining arrays together as one

src/SentinelArrays.jl, test/runtests.jl
sudete on discourse pointed out that there's a corner case not currently
covered when cycling to a new sentinel value. We might try to be
`setindex!`ing a value that is equal to our sentinel value, so we go to
pick a new sentinel, and it might be possible for the newly chosen
sentinel to be equal to the current sentinel, which would pass the "new
sentinel" check because it doesn't exist in the current array. The fix
here is to ensure the newly chosen sentinel is also not the same as the
existing sentinel
=> Fix a rare corner case when cycling a sentinel value

src/SentinelArrays.jl, test/runtests.jl
elements
In `Base.deleteat!`, you're allowed to pass an `Integer` or `UnitRange`
argument, and they work fine with `#undef` elements, but when passing
`inds` or `AbstractVector{Bool}`, elements are accessed, causing
`UndefRefError`s. We put a work-around in place until this inconsistency
can be resolved in Base.
Fixes https://github.com/JuliaData/SentinelArrays.jl/issues/18
=> Work around an inconsistency when deleting from arrays with #undef

src/chainedvector.jl, test/runtests.jl
This line must have been from an inadvertent code refactor splitting
getindex into index + getindex. We don't need to access individual
elements when just determining the chunk and chunk index from overall
index. This caused an issue (reported by @ararslan on slack) in
deleteat! which uses `index` to figure out what to delete.
=> Remove unnecessary code in ChainedVector index

src/chainedvector.jl, src/missingvector.jl, test/runtests.jl
Fixes https://github.com/JuliaData/CSV.jl/issues/690. The issue here is we weren't
testing or accounting for the case when the `inds` arguement to deleteat! is empty.
This comes up in practice from `dropmissing!` in DataFrames.jl when there are no missing
values in a column, it still calls `deleteat!` with the empty array.
The fix is pretty straightforward: we can just remove the bounds checks here because
we're doing the bounds check in the underlying `::Integer` method anyway.
=> Fix deleteat! with empty inds array

src/missingvector.jl, test/runtests.jl
On 32-bit systems having `MissingVector` return a length of `Int64` is problematic when working with DataFrames:
```julia
julia> using DataFrames, SentinelArrays
julia> df = DataFrame(:a => MissingVector(0));
julia> size(df, 1)
ERROR: TypeError: in typeassert, expected Int32, got Int64
Stacktrace:
[1] nrow(::DataFrame) at /home/omus/.julia/packages/DataFrames/lfoTw/src/dataframe/dataframe.jl:346
[2] size(::DataFrame, ::Int32) at /home/omus/.julia/packages/DataFrames/lfoTw/src/abstractdataframe/abstractdataframe.jl:323
[3] top-level scope at REPL[13]:1
julia> typeof(length(MissingVector(0)))
Int64
```
=> `MissingVector` length should be of type Int

Project.toml, src/chainedvector.jl, test/runtests.jl
Fixes #27. The issue here is that `iterate` for `ChainedVector` was
assuming that underlying array chains wouldn't have zero-length. If a
user is doing a lot of filtering/deleting, however, it might be the case
that certain chunks end up with zero-length (though we do try to prune
those out when possible, so I'm still a little unsure how we get in this
state). Nevertheless, this assumption is a bit optimistic, and we can do
better by just checking if the next chunk is zero-length when iterating
and moving on to the next chunk if so.
=> Fix iteration issue when chains have zero-length

src/SentinelArrays.jl, src/chainedvector.jl, test/runtests.jl
Previously, we were taking the most naive route possible. These new
algorithms are now much faster and attempt to take as many fast paths as
possible. For SentinelArray, we use the Base definition for all cases
except when a SentinelArray uses `#undef` for sentinel and has multiple
deletions, since the Base algorithm is inconsistent in allowing `#undef`
to be deleted. We copy-paste the Base algorithm in that case and handle
the `#undef`s specially.
For ChainedVector, we use a new algorithm that iterates indices to
delete and accumulates them per "chunk", thus moving from an algorithm
of one deletion per index, to one deletion call per chunk, which makes
it must faster.
Fixed #23.
=> Make deletat! for SentinelArray/ChainedVector much faster

src/SentinelArrays.jl, test/runtests.jl
Fixes #32. The issue here was a confusion between using deleteat and
_deleteend from Base, so we ended up deleting more elemnts than we
should.
=> Fix deleteat for SentinelArrays with undef and integer inds

src/SentinelArrays.jl, test/runtests.jl
Fixes #34
It seems that this improves `getindex` timing but reduces `copy` time (which needs to convert the sentinel):
Before this PR:
```
julia> x = SentinelArray(rand(10^6));
julia> @btime copy($x);
442.980 μs (3 allocations: 7.63 MiB)
julia> @btime similar($x);
251.363 μs (6 allocations: 7.63 MiB)
julia> @btime $x[10^5:-1:1];
173.375 μs (6 allocations: 781.50 KiB)
```
This PR:
```
julia> x = SentinelArray(rand(10^6));
julia> @btime copy($x);
1.412 ms (2 allocations: 8.58 MiB)
julia> @btime similar($x);
265.543 μs (2 allocations: 8.58 MiB)
julia> @btime $x[10^5:-1:1];
155.686 μs (2 allocations: 879.02 KiB)
```
Still - I believe that all these operations are one-time only, so even the regression for `copy` is acceptable I think (and `copy` is not that bad - it is quite fast anyway). The …
=> Make copy, similar and getindex fallback to Array

src/chainedvector.jl, test/runtests.jl
Fixes #36. The issue here is when a deleteat! was called with integer
indices that spanned multiple array chains, the ChainedVector index
trackers got messed up. We were trying to keep track of what the indices
should be while iterating through chains and deleting, but that's pretty
complicated to get right because when you skip chains, you need to go
back and update them. Anyway, the solution is to stop trying to update
while deleting, and just reset all the indices when we're done with all
the deleting. That ensures the indices will be correct, no matter what
or how many chains were affected by deleting.
=> Fix deleteat on ChainedVector that spans multiple array chains

src/SentinelArrays.jl, src/chainedvector.jl, test/runtests.jl
Fixes #38. The issue here was when deleting spanned multiple chunks of a
ChainedVector, we were then going through and "cleaning up" the chunks
after filtering and were deleting the chunks via forward iteration,
which messed up deleting as the later chunks changed index. By deleting
the chunks in reverse, we ensure hte correct chunks are removed.
=> Fix deleteat! on ChainedVector when multiple chunks are deleted

src/chainedvector.jl, test/chainedvector.jl
Fixes issue #45. The issue here is that the `Base.append!`
implementation relies on calling `first(eachindex(items))`, which has
now been optimized to return a custom type for `ChainedVector`. The
quick work-around is we just overload `Base.append!` when the appending
items is `ChainedVector`, since the definition is so small anyway. If we
end up hearing of other issues with this custom `eachindex` on
`ChainedVector`, we may need to move it back to a more traditional
definition.
=> Fix append on Vector with ChainedVector

src/SentinelArrays.jl
A different seed for each RNG element removes potential conflicts between sentinel values.
This may be a problem in reading many files simultaneously as evidenced by https://github.com/JuliaData/CSV.jl/issues/839
=> Removes conflicts between sentinels values

src/chainedvector.jl, test/chainedvector.jl
Fixes https://github.com/JuliaData/CSV.jl/issues/842. I admit to not
exactly understand why this is needed, except that the `InvertedIndex`
type ends up hitting a generic `axes` method in Base where `size` is
expected to be defined on the ChainedVector `IndexIterator` type.
=> Define size for ChainedVector IndexIterator

src/chainedvector.jl, test/chainedvector.jl
Hopefully resolves issues like those raised in #52 (which this fixes
specifically). To make `ChainedVectorIndex` act like a normal array
index, we need to carry around the "total index" value instead of just
the current array + local array index. We also add some simple integer
definitions for `ChainedVectorIndex` so it can act like an Integer. An
alternative strategy would be to just define appropriate promote/convert
definitions and not arithmetic/comparison directly.
=> Make ChainedVectorIndex <: Integer

src/chainedvector.jl
Including this method causes an ambiguity error and isn't needed anyway,
since we support the right convert methods for ChainedVectorIndex.
Fixes #54
=> Remove unnecessary generic getindex method for ChainedVectorIndex

src/chainedvector.jl, test/chainedvector.jl
Fixes #65. Because we were defining operations like `==` for a mix of
`ChainedVectorIndex` and `Integer`, we introduced ambiguities when
comparing two `ChainedVectorIndex`. The fix here is as the abiguity
error suggests, defining the missing operation.
=> Avoid ambiguities for basic ChainedVectorIndex operations

src/chainedvector.jl, test/chainedvector.jl
Fixes #67. Because we overload `copy` to return a normal `Vector`
instead of `ChainedVector`, we need to define `Base.unaliascopy` to
return an actual `ChainedVector` copy.
=> Define Base.unaliascopy for ChainedVector

src/chainedvector.jl, test/chainedvector.jl
Base Julia does not allow `Bool` index in `insert!`:
```
julia> insert!([1, 2], true, 3)
ERROR: ArgumentError: invalid index: true of type Bool
julia> insert!(ChainedVector([[1, 2]]), true, 3)
3-element ChainedVector{Int64, Vector{Int64}}:
3
1
2
```
=> make insert! consistent with Base Julia

src/chainedvector.jl, test/chainedvector.jl
The `BitVector(::AbstractVector{Bool})` method uses the `Base.nextind` method to increment the inds from `eachindex` that I didn't know existed. I'm not exactly sure why they use that instead of just iterating `eachindex` but it turns out we can define `nextind` to be pretty efficient for `ChainedVectorIndex` since we basically already have that logic in `eachindex(::ChainedVector)`.
Fixes the issue reported in https://github.com/JuliaData/SentinelArrays.jl/issues/74.
=> Define nextind/prevind for ChainedVectorIndex

src/SentinelArrays.jl, test/runtests.jl
On my system that gets rid of about 100ms of package load time.
Before:
```
348.6 ms  SentinelArrays 31.04% compilation time
```
After:
```
242.6 ms  SentinelArrays
```
My understanding is that the global RNG is thread-safe (and thread-local) since Julia 1.3, which is the min Julia version for this package, so I don't think there is actually any need for this package specific thread-local RNG creation, right? See https://github.com/JuliaLang/julia/blob/master/HISTORY.md#multi-threading-changes-5.
=> Use global system RNG

src/chainedvector.jl, test/chainedvector.jl
Fixes https://github.com/JuliaData/SentinelArrays.jl/issues/79. We only treated the `len` argument in our `ChainedVector` `similar` method as an `Integer` and not if it was a `OneTo`.
=> Fix processing of ind in similar

src/SentinelArrays.jl
Because `T` is poorly-inferred, it may be best to hide operations that are vulnerable to invalidation behind a `Base.invokelatest`.
=> Fix some invalidations

src/chainedvector.jl, test/chainedvector.jl
Fixes https://github.com/apache/arrow-julia/issues/418. The issue here is that a ChainedVectorIndex is really only valid for the ChainedVector it came from, so assert that in checkbounds, which can be compiled away w/ the checkbounds functionality if an indexing operation is marked `@inbounds`.
=> Add an assert in ChainedVectorIndex checkbounds

src/BufferedVectors.jl, test/BufferedVectors.jl
The OOB read was caught by https://github.com/JuliaLang/julia/pull/51319. Although this code seems like it probably should be deleted, since it appears to be identical in features to Array but with worse heuristics and implementations.
=> fix out-of-bounds bug in BufferedVector

Project.toml
Following this guide https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958#update-november-2nd-2023-how-do-i-determine-what-the-compat-entry-should-be-for-a-stdlib-1, since we are supporting Julia 1.3, we use the `"<0.0.1, 1"` compat bounds.
=> Add compat bounds for `Dates` and `Random`

src/chainedvector.jl, test/chainedvector.jl
Draft PR to fix #97
How do we add proper tests for this in the least disruptive way?
=> Fix argmin and argmax

src/chainedvector.jl
Currently the ChainedVector constructor has bad performance if the args have empty entries.
```
import Random
struct MyType
x::Float64
y::Float64
end
x1 = [ MyType[MyType(rand(), rand()) for _ in 1:Random.rand(1:6)] for _ in 1:1_000_000];
@time ChainedVector(x1);  # 0.017 secs
x2 = [ MyType[MyType(rand(), rand()) for _ in 1:Random.rand(0:5)] for _ in 1:1_000_000];
@time ChainedVector(x2);  # 24 secs
```
Note that the difference comes only from the fact that x2 might have empty entries whereas x1 doesn't.
The problem is that the function cleanup! has runtime proportional to the number of elements times the number of elements which are empty vectors.
```
function cleanup_original!(arrays, inds)
@assert length(arrays) == length(inds)
for i = length(arrays):-1:1
if !isassigned(arrays, i) || …
```
=> Bugfix ChainedVector constructor performance

src/chainedvector.jl, test/chainedvector.jl
Before:
```julia
julia> using SentinelArrays, Chairmarks
julia> function f(inputs, range)
ChainedVector(inputs)[range]
end
f (generic function with 1 method)
julia> function g(inputs, range)
reduce(vcat, inputs)[range]
end
g (generic function with 1 method)
julia> vinputs = [rand(Float32, rand(1024:2048)) for _ = 1:90];
julia> @b f(vinputs, 1:95000)
64.666 μs (9 allocs: 372.125 KiB)
```
After:
```julia
julia> @b f(vinputs, 1:95000)
13.875 μs (9 allocs: 372.125 KiB)
```
=> Improve getindex performance on ChainedVector with UnitRanges

Project.toml, src/chainedvector.jl, test/chainedvector.jl
Fixes #107 and fixes #109 by using `copyto!` instead of `unsafe_copyto!`.
Additionally, I fixed type stability of `getindex` and support for empty `ChainedVector`s.
Currently on the main branch:
```julia
julia> x = ChainedVector([[1, 2], [3, 4]]);
julia> x[Int[]]
0-element ChainedVector{Int64, Vector{Int64}}
julia> x[2:1]
0-element ChainedVector{Int64, Vector{Int64}}
julia> x[[2,3]]
2-element Vector{Int64}:
2
3
julia> x[2:3]
2-element Vector{Int64}:
2
3
julia> x = ChainedVector([[]]);
julia> x[Int[]]
0-element ChainedVector{Any, Vector{Any}}
julia> x[2:1]
0-element ChainedVector{Any, Vector{Any}}
```
With this PR:
```julia
julia> x = ChainedVector([[1, 2], [3, 4]]);
julia> x[Int[]]
Int64[]
julia> x[2:1]
Int64[]
julia> x[[2,3]]
2-element Vector{Int64}:
2
3
julia> x[2:3]
2-element …
```
=> Fix `getindex`

src/chainedvector.jl, test/chainedvector.jl
Fix https://github.com/JuliaData/SentinelArrays.jl/issues/110
The last chunk wasn't handled properly when resizing, leading to errors downstream in sort, unique! and so on.
=> Fix resize! on ChainedVector

src/chainedvector.jl
I've no idea why this function is defined, its not used anyhwere, so we might be able to remove it all together.
=> remove unused function `over()`
